include theos/makefiles/common.mk

export GO_EASY_ON_ME=1
export SDKVERSION=5.0

MailKeyboardHide_FRAMEWORKS=UIKit QuartzCore
TWEAK_NAME = MailKeyboardHide
MailKeyboardHide_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
