include theos/makefiles/common.mk

export GO_EASY_ON_ME=1
export SDKVERSION=5.0

UShare_FRAMEWORKS=UIKit QuartzCore
UShare_PRIVATE_FRAMEWORKS=YouTube
TWEAK_NAME = UShare
UShare_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
