include theos/makefiles/common.mk

export GO_EASY_ON_ME=1
export SDKVERSION=5.0

funnycaller_FRAMEWORKS=UIKit QuartzCore
TWEAK_NAME = funnycaller
funnycaller_FILES = Tweak.xm

SUBPROJECTS=funnycaller

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
